services:
  odoo:
    build:
      context: .
      dockerfile: dockerfile
    # Because we use host network, the port opened by your container will be automatically opened.
    # Please make sure there are no ports collide. (sudo netstat -tulpn)
    # Set the ports below the same as you have set in your .env file.
    #ports:
    #  - "9000:8069"
    #  - "19001:8072"
    network_mode: "host"
    volumes:
     - ./datadir:/opt/odoo/datadir
     - ./log:/var/log/odoo
    environment:
     - PORT
     - GEVENT_PORT
     - WORKERS
     - MAX_CRON_THREADS
     - LIMIT_MEMORY_SOFT
     - LIMIT_MEMORY_HARD
     - LIMIT_TIME_CPU
     - LIMIT_TIME_REAL
     - LIMIT_TIME_REAL_CRON
     - LIMIT_REQUEST
     - TRANSIENT_AGE_LIMIT
     - DATA_DIR
     - DB_USER
     - DB_NAME
     - DB_HOST
     - DB_PORT
     - DB_MAXCONN
    env_file:
      - .env
    secrets:
      - db_user
      - db_password
    restart: always

secrets:
  db_user:
    file: .secrets/db_user
  db_password:
    file: .secrets/db_password
