# you can setup this variable to the version of python you want to use in .env file and build the image using docker-compose.yml file
ARG PYTHON_VERSION=3.10-bookworm

FROM python:$PYTHON_VERSION

ARG APT_ADDITIONAL_PACKAGES
ARG INSTALL_LIBREOFFICE
ARG POSTGRESQL_VERSION
ARG VSCODE_DIRECT_DOWNLOAD_URL
ARG WKHTMLTOPDF_DIRECT_DOWNLOAD_URL
ARG APT_RESOURCE_URL
ARG POSTGRESQL_CUSTOM_REPO_URL

RUN if [ -n "$APT_RESOURCE_URL" ]; then \
        echo "$APT_RESOURCE_URL" > /etc/apt/sources.list; \
    fi

# install odoo dependencies
RUN apt update; \
    apt install -y wget software-properties-common ca-certificates build-essential libxslt-dev libzip-dev libldap2-dev libsasl2-dev node-less libpq-dev tmux xfonts-75dpi fontconfig libxrender1 xfonts-base libcups2-dev

RUN if [ -n "$WKHTMLTOPDF_DIRECT_DOWNLOAD_URL" ] && { [ "$WKHTMLTOPDF_DIRECT_DOWNLOAD_URL" != "${WKHTMLTOPDF_DIRECT_DOWNLOAD_URL#[http://]}" ] || [ "$WKHTMLTOPDF_DIRECT_DOWNLOAD_URL" != "${WKHTMLTOPDF_DIRECT_DOWNLOAD_URL#[https://]}" ]; }; then \
        filename="wkhtmltox_installer.deb"; \
        wget -O "$filename" $WKHTMLTOPDF_DIRECT_DOWNLOAD_URL; \
        if [ $? -ne 0 ]; then \
            echo "Error downloading wkhtmltopdf. Exiting." >&2; \
            exit 1; \
        fi; \
        apt install -y "./$filename"; \
        rm "$filename"; \
    else \
        echo "No direct download URL provided for wkhtmltopdf. Skipping installation." >&2; \
    fi

RUN apt install -y cabextract; \
    curl -O http://ftp.cn.debian.org/debian/pool/contrib/m/msttcorefonts/ttf-mscorefonts-installer_3.8.1_all.deb; \
    dpkg -i ./ttf-mscorefonts-installer_3.8.1_all.deb; \
    rm ./ttf-mscorefonts-installer_3.8.1_all.deb

RUN if [ "$INSTALL_LIBREOFFICE" = "Y" ]; then \
        apt --no-install-recommends -y install libreoffice; \
    fi

RUN if [ -n "$POSTGRESQL_VERSION" ]; then \
        install -d /usr/share/postgresql-common/pgdg; \
        curl -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc --fail https://www.postgresql.org/media/keys/ACCC4CF8.asc; \
        . /etc/os-release; \
        REPO_URL="${POSTGRESQL_CUSTOM_REPO_URL:-https://apt.postgresql.org}"; \
        sh -c "echo 'deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] $REPO_URL/pub/repos/apt $VERSION_CODENAME-pgdg main' > /etc/apt/sources.list.d/pgdg.list"; \
        apt update; \
        apt install -y postgresql-client-$POSTGRESQL_VERSION; \
    else \
        apt install -y postgresql-client; \
    fi

RUN if [ -n "$VSCODE_DIRECT_DOWNLOAD_URL" ] && { [ "$VSCODE_DIRECT_DOWNLOAD_URL" != "${VSCODE_DIRECT_DOWNLOAD_URL#[http://]}" ] || [ "$VSCODE_DIRECT_DOWNLOAD_URL" != "${VSCODE_DIRECT_DOWNLOAD_URL#[https://]}" ]; }; then \
        filename="vscode_installer.deb"; \
        wget -O "$filename" $VSCODE_DIRECT_DOWNLOAD_URL; \
        if [ $? -ne 0 ]; then \
            echo "Error downloading VS Code. Exiting." >&2; \
            exit 1; \
        fi; \
        apt install -y "./$filename"; \
        rm "$filename"; \
    fi

RUN if [ -n "$APT_ADDITIONAL_PACKAGES" ]; then \
        apt install -y $APT_ADDITIONAL_PACKAGES; \
    fi

RUN groupadd -g 8069 odoo; \
    useradd -r -u 8069 -g 8069 -m -s /bin/bash odoo

RUN mkdir -p /var/log/odoo; \
    chown odoo: /var/log/odoo; \
    mkdir -p /opt/odoo; \
    chown odoo: /opt/odoo; \
    mkdir /var/lib/odoo; \
    chown odoo: /var/lib/odoo

# Install python dependencies first to leverage cache
COPY --chown=odoo:odoo ./requirements.txt /opt/odoo/requirements.txt
USER odoo
WORKDIR /opt/odoo
RUN export MAKEFLAGS="-j $(nproc)"; \
    pip install -r ./requirements.txt

# Switch back to root for further setup
USER root

# Copy configurations and static utilities
# Copy configurations and static utilities
COPY --chown=odoo:odoo ./entrypoint.sh /opt/odoo/entrypoint.sh
COPY --chown=odoo:odoo ./utilities/odoo-shell /usr/local/bin/odoo-shell
COPY --chown=odoo:odoo ./utilities/odoo-module-upgrade /usr/local/bin/odoo-module-upgrade
COPY ./utilities/install-font.sh /usr/local/bin/install-font

# Set permissions
RUN chmod 550 /opt/odoo/entrypoint.sh; \
    chmod 550 /usr/local/bin/odoo-shell; \
    chmod 550 /usr/local/bin/odoo-module-upgrade; \
    chmod 555 /usr/local/bin/install-font


USER odoo

# expose the default port of odoo (Will need to be set in the .env file and docker-compose.yml)
EXPOSE 8069
EXPOSE 8072

# set the command to run odoo instance using entrypoint.sh
ENTRYPOINT [ "/opt/odoo/entrypoint.sh" ]
