# press ctrl + f and search "enter" string to find which value should you change.

services:
  odoo:
    # push the image to Container registry (enter and choose one)
    ## Use the image from the GitHub Container Registry; (find this string 'enter github' to link the image to repoistory)
    # image: ghcr.io/enter_username/enter_project_name:enter_version
    ## Use the image from the Docker Hub
    # image: enter_username/enter_project_name:enter_version
    ## Use the image from the Gitlab Container Registry
    # image: registry.gitlab.com/enter_username/enter_project_name:enter_version

    build:
      context: .
      dockerfile: dockerfile
      # Add labels to connect to github repository (enter github)
      # labels:
        # - org.opencontainers.image.source=https://github.com/enter_username/enter_repository
    # Because we use host network, the port opened by your container will be automatically opened.
    # Please make sure there are no ports collide. (sudo netstat -tulpn)
    # Set the ports below the same as you have set in your .env file.
    #ports:
    #  - "9000:8069"
    #  - "19001:8072"
    network_mode: "host"
    entrypoint: [ "/opt/odoo/entrypoint.sh" ]
    command: [ "-c", "/etc/odoo/odoo.conf" ]
    volumes:
     - ${ODOO_DATADIR_SERVICE}:${ODOO_DATADIR_SERVICE}
     - ${ODOO_LOG_DIR_SERVICE}:${ODOO_LOG_DIR_SERVICE}
    environment:
     - DB_USER
     - DB_NAME
     - DB_HOST
     - DB_PORT
     - DB_MAXCONN
     - PORT
     - GEVENT_PORT
     - WORKERS
     - MAX_CRON_THREADS
     - LIMIT_MEMORY_SOFT
     - LIMIT_MEMORY_HARD
     - LIMIT_TIME_CPU
     - LIMIT_TIME_REAL
     - LIMIT_TIME_REAL_CRON
     - LIMIT_REQUEST
     - TRANSIENT_AGE_LIMIT
     - DATA_DIR
     - SERVICE_NAME
     - ODOO_DATADIR_SERVICE
     - ODOO_LOG_DIR_SERVICE
    env_file:
      - .env
    secrets:
      - db_user
      - db_password
    restart: always

secrets:
  db_user:
    file: .secrets/db_user
  db_password:
    file: .secrets/db_password
