# press ctrl + f and search "enter" string to find which value should you change.

services:
  odoo:
    image: ${ODOO_IMAGE_NAME:-$SERVICE_NAME:latest}

    build:
      context: .
      dockerfile: dockerfile
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}
      # Add labels to connect to github repository (enter github)
      labels:
        - org.opencontainers.image.source=${ODOO_IMAGE_SOURCE:-"no source"}
    # Because we use host network, the port opened by your container will be automatically opened.
    # Please make sure there are no ports collide. (sudo netstat -tulpn)
    # Set the ports below the same as you have set in your .env file.
    #ports:
    #  - "9000:8069"
    #  - "19001:8072"
    network_mode: "host"
    entrypoint: [ "/opt/odoo/entrypoint.sh" ]
    command: [ "-c", "/etc/odoo/odoo.conf" ]
    volumes:
     - ${ODOO_DATADIR_SERVICE}:${ODOO_DATADIR_SERVICE}
     - ${ODOO_LOG_DIR_SERVICE}:${ODOO_LOG_DIR_SERVICE}
    environment:
     - DB_USER
     - DB_NAME
     - DB_HOST
     - DB_PORT
     - DB_MAXCONN
     - PORT
     - GEVENT_PORT
     - WORKERS
     - MAX_CRON_THREADS
     - LIMIT_MEMORY_SOFT
     - LIMIT_MEMORY_HARD
     - LIMIT_TIME_CPU
     - LIMIT_TIME_REAL
     - LIMIT_TIME_REAL_CRON
     - LIMIT_REQUEST
     - TRANSIENT_AGE_LIMIT
     - DATA_DIR
     - SERVICE_NAME
     - ODOO_DATADIR_SERVICE
     - ODOO_IMAGE_NAME
     - ODOO_IMAGE_SOURCE
     - ODOO_LOG_DIR_SERVICE
     - PYTHON_VERSION
    env_file:
      - .env
    secrets:
      - db_user
      - db_password
    restart: always

secrets:
  db_user:
    file: .secrets/db_user
  db_password:
    file: .secrets/db_password
